- wecube-core/src/main/java/com/webank/wecube/core/parser/PluginConfigXmlValidator.java
- wecube-core/src/main/resources/plugin/plugin-config-v2.xsd
- wecube-core/src/test/java/com/webank/wecube/core/parser/PluginConfigXmlValidatorTest.java
- wecube-core/src/test/resources/plugin/plugin-config-v2.xsd
- wecube-core/src/test/resources/plugin/sample-plugin-config-v2-false.xml
- wecube-core/src/test/resources/plugin/sample-plugin-config-v2-false2.xml
- wecube-core/src/test/resources/plugin/sample-plugin-config-v2-false3.xml
- wecube-core/src/test/resources/plugin/sample-plugin-config-v2-false4.xml
- wecube-core/src/test/resources/plugin/sample-plugin-config-v2-false5.xml
- wecube-core/src/test/resources/plugin/sample-plugin-config-v2-false6.xml
- wecube-core/src/test/resources/plugin/sample-plugin-config-v2.xml
add PluginConfigXmlValidator and its xsd, test xml, false test xml file.
> 340 xml schema

- platform-core/src/main/java/com/webank/wecube/platform/core/domain/SystemVariable.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterface.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterfaceParameter.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginInstance.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageAttribute.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageAuthority.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageDependency.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageEntity.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenu.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesDocker.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesMysql.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageRuntimeResourcesS3.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageAttributeDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageEntityDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
- platform-core/src/main/java/com/webank/wecube/platform/core/utils/constant/DataModelDataType.java
- platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParserTest.java
- platform-core/src/test/resources/plugin-config-v2.xsd
- platform-core/src/test/resources/register-for-parser-test.xml
核心代码在PluginPackageXmlParser，单元测试PluginPackageXmlParserTest
> #341 parse plugin package definition xml

- wecube-wiki/docs/developer/wecube_developer_guide_en.md
- wecube-wiki/docs/install/wecube_compile_guide_en.md
- wecube-wiki/docs/install/wecube_install_guide_en.md
> 454 update en doc

- platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginConfigController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigCopyHelper.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
> 442 fix bugs by test

- platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageResourceFileController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageResourceFile.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageResourceFilesDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageResourceFileRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageResourceFileService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
- platform-core/src/main/resources/database/01.wecube.schema.sql
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageResourceFileControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
- platform-core/src/test/resources/database/01.wecube.schema.sql
> 437 resource file handling

- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageEntity.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageAttributeDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageEntityDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageAttributeRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageEntityRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
- platform-core/src/main/resources/database/01.wecube.schema.sql
- platform-core/src/test/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceTest.java
- platform-core/src/test/resources/database/01.wecube.schema.sql
> 467 dynamic datamodel

- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
- platform-core/src/main/resources/database/01.wecube.schema.sql
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginPackageRepositoryTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginPackageResourceFileRepositoryTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
- platform-core/src/test/resources/database/01.wecube.schema.sql
> #442 fix ui exists logic

- wecube-core/pom.xml
> #543 Upgrade jackson-databind version to [2.9.10.1,)

- platform-core/src/main/java/com/webank/wecube/platform/core/commons/XPathEvaluator.java
- platform-core/src/main/resources/plugin/plugin-config-v2.xsd
- platform-core/src/test/resources/plugin-config-v2.xsd
- platform-core/src/test/resources/plugin/plugin-config-v2.xsd
update xsd to support isDynamic temporarily.
> #494 update xsd to support isDynamic

- platform-core/src/main/resources/plugin/plugin-config-v2.xsd
- platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginConfigXmlValidatorTest.java
- platform-core/src/test/resources/plugin-config-v2.xsd
- platform-core/src/test/resources/plugin/plugin-config-v2.xsd
- platform-core/src/test/resources/plugin/sample-plugin-config-without-data-model-entity.xml
mark entity element as optional
> #494 update entity element as optional

- platform-core/src/test/java/com/webank/wecube/platform/core/DatabaseBasedTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/UserManagementServiceTest.java
> 554 sort menu by code

- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceTest.java
Fixed #560 fix empty data model issue
> 560 fix empty data model issue

- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
Fixed #560 allow entity to be null in plugin config
> #560 allow entity to be null in plugin config

- platform-core/src/main/java/com/webank/wecube/platform/core/commons/ApplicationProperties.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/resource/DockerContainerManagementService.java
- platform-core/src/main/resources/application.yml
> 577 support slatstack plugin

- platform-gateway/src/main/java/com/webank/wecube/platform/gateway/filter/factory/DynamicRouteGatewayFilterFactory.java
> #584 Attach query param when building new URI

- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageDataModelDtoValidator.java
- platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginPackageDataModelDtoValidatorTest.java
- platform-core/src/test/resources/plugin/sample-plugin-config-with-data-model-entity-attribute-without-datatype.xml
- platform-core/src/test/resources/plugin/sample-plugin-config-with-data-model-entity-but-ref-attribute-name-missing.xml
- platform-core/src/test/resources/plugin/sample-plugin-config-with-data-model-entity.xml
> #560 support null entity data model

- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
> 592 plugin onandoff patch

- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
- platform-core/src/main/resources/plugin/plugin-config-v2.xsd
> #559 fix data model issue

- platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginConfigController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigInterfaceDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigInterfaceParameterDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/handler/GlobalExceptionHandler.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigInterfaceRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
> 593 plugin actions by entity

- platform-core/src/main/java/com/webank/wecube/platform/core/support/gateway/GatewayServiceStub.java
> #622 Fix bug - call gateway meet I/O error

- .circleci/config.yml
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterface.java
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginRepositoryIntegrationTest.java
- pom.xml
Fixed #631 fix parameters missing issue after interface enabled
> #631 fix parameters missing issue after interface enabled

- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageEntityDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
> #655 update entity reference for dynamic model

- platform-core/src/main/java/com/webank/wecube/platform/core/utils/Constants.java
> #661 rollback package name regex for now

- platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/DataModelExpressionListener.java
- platform-core/src/main/java/com/webank/wecube/platform/core/parser/datamodel/DataModelExpressionParser.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/DataModelExpressionService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/DataModelExpressionServiceImpl.java
- platform-core/src/main/java/com/webank/wecube/platform/core/support/datamodel/DataModelExpressionDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/support/datamodel/TreeNode.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/DataModelExpressionServiceTest.java
Complete #649 ready for merge.
> 649 workflow preview tree

- platform-core/src/main/java/com/webank/wecube/platform/core/service/DataModelExpressionService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/DataModelExpressionServiceImpl.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/DataModelExpressionServiceTest.java
> 532 process layout hotfix

- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
- platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginPackageDataModelDtoValidatorTest.java
- platform-core/src/test/resources/plugin/sample-plugin-config-output-parameter-with-mappingtype.xml
> #781 output parameter to support mapping type

- platform-core/src/main/java/com/webank/wecube/platform/core/domain/SystemVariable.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
> #741 Fix failed unit test cases

- Makefile
Normal setting of a variable - values within it are recursively expanded when the variable is used, not when it's declared
Above is the reason why timestamp will be changed when it is used.
> 734  use immediate set assignment instead of lazy set.

- wecube-portal/src/api/base.js
> Optimize data deconstruction

- platform-core/pom.xml
- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
- platform-core/src/main/resources/database/01.wecube.schema.sql
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginPackageAttributeRepositoryTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginPackageEntityRepositoryTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginPackageDataModelDtoValidatorTest.java
- platform-core/src/test/resources/plugin/sample-plugin-config-with-data-model-entity-attribute-without-description.xml
> #791 allow null description for entity and attribute in datamodel

- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigInterfaceParameterDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
> #738 throw exception if required parameter not set for plugin

- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
> #829 fix #829

- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
- platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParserTest.java
> #862 set default status for system variable when upload package

- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterface.java
remove white space  from id for plugin interface.
> #887 fix id with spaces

- platform-core/src/main/java/com/webank/wecube/platform/core/controller/DataServiceController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/datamodel/NonExpressionService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/datamodel/NonExpressionServiceImpl.java
- platform-core/src/main/java/com/webank/wecube/platform/core/support/datamodel/DataModelServiceStub.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/DataServiceControllerTest.java
> 901 data service retrieve request param

- platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginConfigController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginInstanceController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfig.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginMysqlInstanceRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/plugin/PluginConfigServiceTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/plugin/PluginPackageServiceTest.java
> #845 state control fix for plugins and services

- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginMysqlInstanceRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginMysqlInstanceRepositoryTest.java
> #912 Fix bug - new version package can not use old version package's db

- wecube-portal/src/pages/collaboration/workflow-orchestration.vue
#962 Upgrade bpmn-js configuration
> 962 Upgrade bpmn-js configuration

- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackage.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/plugin/PluginPackageServiceMockTest.java
> 876 add role if not exists in system

- platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginConfigController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
> #783 filter plugin services by entity name

- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigInterfaceRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
> #783 filter plugin services by entity name and null entity name as well

- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginConfigDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginConfigInterfaceRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
> 1019 get all plugin interfaces without entity name when filtering by entity

- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/PluginInstanceServiceTest.java
> #990 pick up running instances for active package only

- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginConfigInterface.java
- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
- platform-core/src/main/resources/plugin/plugin-config-v2.xsd
- platform-core/src/test/java/com/webank/wecube/platform/core/parser/PluginConfigXmlValidatorTest.java
- platform-core/src/test/resources/plugin/register-with-register-name.xml
> 974 support replication interface registration

- wecube-portal/src/pages/collaboration/components/plugin-register.vue
> #1036 Bug fix

- wecube-core/src/test/java/com/webank/wecube/core/service/OperationLogServiceTest.java
- wecube-core/src/test/java/com/webank/wecube/core/service/PluginInstanceServiceTest.java
- wecube-core/src/test/java/com/webank/wecube/core/service/workflow/ProcessDefinitionServiceTest.java
> #376 fix tests on master

- platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
> #1046 system variables not showed up fix

- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageEntityRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginConfigService.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginConfigControllerTest.java
> #1080 fix plugin config save issue

- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceTest.java
> #1103 keep package status unchanged after new data model applied

- wecube-portal/src/pages/collaboration/components/plugin-register.vue
> #1090 Bug fix

- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginInstance.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenu.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenuStatusListener.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/MenuItemDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginInstanceRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageMenuRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/resource/ResourceDataQueryService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/user/RoleMenuServiceImpl.java
- platform-core/src/main/resources/database/01.wecube.schema.sql
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginInstanceRepositoryTest.java
> #1116 plugin menu to support status

- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenu.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/plugin/PluginPackageMenuStatusListener.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/MenuItemDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageMenuRepository.java
- platform-core/src/main/resources/database/01.wecube.schema.sql
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginInstanceRepositoryTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/jpa/PluginPackageMenuRepositoryTest.java
> #1116 fix status issue

- platform-core/src/main/java/com/webank/wecube/platform/core/controller/PluginPackageDataModelController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceTest.java
> 1163 datamodel entity view

- wecube-portal/src/pages/implementation/batch-execution.vue
> #1210 Bug fix

- wecube-portal/src/pages/collaboration/components/plugin-register.vue
> #1095_Bug_fix

- wecube-portal/src/pages/implementation/workflow-execution.vue
#1220 Enhance  workflow excution
> #1220 Enhance  workflow excution

- wecube-portal/src/pages/implementation/workflow-execution.vue
#1220 enhance workflow execution
> 1220 enhance workflow execution

- platform-core/src/main/java/com/webank/wecube/platform/core/dto/workflow/GraphNodeDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/datamodel/ExpressionServiceImpl.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/workflow/WorkflowDataService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/support/datamodel/DataModelServiceStub.java
- platform-core/src/main/java/com/webank/wecube/platform/core/support/datamodel/dto/TreeNode.java
- platform-core/src/main/java/com/webank/wecube/platform/core/utils/CollectionUtils.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/datamodel/ExpressionServiceTest.java
> 1123 entity tree info

- wecube-portal/src/pages/implementation/workflow-execution.vue
#1220 enhance workflow execution
> #1220 enhance workflow execution

- wecube-portal/src/pages/implementation/workflow-execution.vue
> #1220 Update graph label

- wecube-portal/src/pages/collaboration/components/plugin-register.vue
> #1235 Bug fix

- wecube-portal/src/pages/implementation/batch-execution.vue
- wecube-portal/src/pages/implementation/workflow-execution.vue
#1239 Empty canvas when switching buttons
> #1239 Empty canvas when switching buttons

- platform-core/src/main/java/com/webank/wecube/platform/core/utils/JsonUtils.java
- platform-core/src/main/java/com/webank/wecube/platform/core/utils/RestTemplateUtils.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/datamodel/RootlessExpressionServiceTest.java
> 1242 fix test

- platform-core/src/main/java/com/webank/wecube/platform/core/controller/HomeController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/controller/RoleManagementController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/controller/UserManagementController.java
- platform-core/src/main/java/com/webank/wecube/platform/core/domain/RoleMenu.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/user/RoleMenuRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/MenuService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/user/RoleMenuService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/user/RoleMenuServiceImpl.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/user/UserManagementService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/user/UserManagementServiceImpl.java
- platform-core/src/main/resources/database/01.wecube.schema.sql
- platform-core/src/main/resources/database/02.wecube.system.data.sql
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/user/RoleMenuServiceTest.java
> 1168 menu authority

- platform-core/src/main/java/com/webank/wecube/platform/core/support/datamodel/DataModelServiceStub.java
- platform-core/src/test/java/com/webank/wecube/platform/core/BaseSpringBootTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/DataServiceControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/datamodel/ExpressionServiceTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/datamodel/RootlessExpressionServiceTest.java
> 1253 dme service authentication

- platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/repository/UserRoleRelationshipRepository.java
- platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/service/UserRoleRelationshipService.java
> 1256 bug get user by role

- wecube-portal/src/pages/implementation/workflow-execution.vue
#1274 Enhance history workflow
> #1274 Enhance history workflow

- platform-core/src/main/resources/application.yml
> #1260 update application.yml with new sub-system-code

- platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/dto/CreateRoleDto.java
- platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/entity/SysRoleEntity.java
- platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/service/RoleService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/user/RoleDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
- platform-core/src/main/resources/application.yml
- wecube-portal/src/locale/i18n/en-US.json
- wecube-portal/src/locale/i18n/zh-CN.json
- wecube-portal/src/pages/admin/user-role-management.vue
> 1234 role email

- platform-core/src/main/java/com/webank/wecube/platform/core/dto/user/RoleDto.java
> #1234 update RoleDto

- platform-core/src/main/java/com/webank/wecube/platform/core/service/user/UserManagementServiceImpl.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/user/RoleMenuServiceTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/user/UserManagementServiceTest.java
> 1271 rest template refactor

- wecube-portal/src/pages/collaboration/components/plugin-register.vue
> #1281 Upgrade plugin register

- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
> hot fix - Can not find the running plugin instance

- wecube-portal/src/pages/implementation/workflow-execution.vue
> #1289 Fix bug

- wecube-portal/src/pages/implementation/workflow-execution.vue
#1284 Adaptive font size for workflow
> #1284 Adaptive font size for workflow

- wecube-portal/src/pages/collaboration/components/plugin-register.vue
> #1277 Fix bug

- wecube-portal/src/pages/implementation/workflow-execution.vue
> 1190 bug fix

- wecube-portal/src/pages/collaboration/components/plugin-register.vue
> #1277  Fix bug

- wecube-portal/src/pages/implementation/batch-execution.vue
> #1229 Fix bug

- wecube-portal/src/pages/implementation/workflow-execution.vue
> #1308 zoom modal

- wecube-portal/src/pages/implementation/workflow-execution.vue
> 1326 Bug fix

- wecube-portal/src/pages/implementation/workflow-execution.vue
> #1325 Bug fix

- wecube-portal/src/pages/implementation/workflow-execution.vue
#1308 Enhance node execution result display
> 1308 upgrade workflow exection

- wecube-portal/src/pages/implementation/batch-execution.vue
> #1342 Bug fix

- wecube-portal/src/pages/implementation/workflow-execution.vue
> #1346 Workflow node display

- wecube-portal/src/pages/implementation/batch-execution.vue
> 1356 enhance batch exection

- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/ResourceServerRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
Fixed #1376, find docker srouce server should use hostIp+type
> #1376 - Fixed #1376, find docker srouce server should use hostIp+type

- platform-auth-server/src/main/resources/application.yml
- platform-gateway/src/main/resources/application-demo-uat.yml
- platform-gateway/src/main/resources/application-dev2.yml
- platform-gateway/src/main/resources/application-eKyc.yml
Fixed #1400, remove sensitive info
> #1400 - Fixed #1400, remove sensitive info

- wecube-portal/src/api/base.js
- wecube-portal/src/const/export-file.js
> #1383 Optimize export

- platform-core/src/main/java/com/webank/wecube/platform/core/utils/Constants.java
Fixed #1421, remove 'CMDB_URL' from global system variables
> #1421 - Fixed #1421, remove 'CMDB_URL' from global system variables

- platform-auth-server/src/main/resources/application.yml
Fixed #1425, modify default timeout duration of token to 10 min
> #1425 - Fixed #1425, modify default timeout duration of token to 10 min

- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/SystemVariableRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
Fixed #1420, update global system variable when register package
> 1420 fix system variable bugs

- wecube-portal/src/pages/implementation/workflow-execution.vue
> #1418 Query process status

- wecube-portal/src/pages/implementation/workflow-execution.vue
#1418 Clear workflow-exection cache
> #1418 Clear workflow-exection cache

- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/PluginPackageMenuRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/user/RoleMenuRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/user/RoleMenuServiceImpl.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/plugin/PluginPackageServiceMockTest.java
> 1407 hot fix

- platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/controller/LocalRoleManagementController.java
- platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/dto/RoleAuthoritiesDto.java
- platform-auth-server/src/main/java/com/webank/wecube/platform/auth/server/dto/RoleAuthoritiesGrantDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/support/authserver/AsRoleAuthoritiesDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/support/authserver/AuthServerRestClient.java
- platform-core/src/main/java/com/webank/wecube/platform/core/support/authserver/AuthServerRestClientProperties.java
- platform-core/src/test/java/com/webank/wecube/platform/core/controller/PluginPackageControllerTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceTest.java
- platform-core/src/test/java/com/webank/wecube/platform/core/service/plugin/PluginPackageServiceMockTest.java
> 1433 role menu refactory

- platform-core/src/main/java/com/webank/wecube/platform/core/jpa/ResourceServerRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java
Fixed #1443, use hostIp+Type to find record
> #1443 - Fixed #1443, use hostIp+Type to find record

- wecube-portal/src/pages/implementation/workflow-execution.vue
#1418 Bug fix for node data display
> #1418 Bug fix for node data display

- platform-core/src/main/resources/database/02.wecube.system.data.sql
Fixed #1460, remove CMDB_URL from init data sql
> #1460 - Fixed #1460, remove CMDB_URL from init data sql

- wecube-portal/src/pages/collaboration/components/plugin-register.vue
> #1462 Fix bug

- wecube-portal/src/pages/implementation/workflow-execution.vue
#1445 Add log to workflow-execution
> #1445 Add log to workflow-execution

- platform-core/src/main/java/com/webank/wecube/platform/core/service/resource/ResourceManagementService.java
#1472 - Fixed #1472, remove the validation of isAllocated
> #1472 - Fixed #1472, remove the validation of isAllocated

- Makefile
Fixed #1457, support publish images to docker hub
> #1457 - Fixed #1457, support publish images to docker hub

- wecube-portal/src/pages/implementation/workflow-execution.vue
#1474 enhance executive function control
> 1474 enhance executive function control

- wecube-portal/src/pages/collaboration/components/plugin-register.vue
> #1477 Fix bug

- wecube-portal/src/pages/implementation/workflow-execution.vue
#1474 Enhance workflow data echo
> #1474 Enhance workflow data echo

- wecube-portal/src/pages/collaboration/components/plugin-register.vue
> #1477 Add panel control

- wecube-portal/src/locale/i18n/en-US.json
- wecube-portal/src/locale/i18n/zh-CN.json
- wecube-portal/src/pages/collaboration/workflow-orchestration.vue
> #1535 bug fix

- platform-core/src/main/java/com/webank/wecube/platform/core/parser/PluginPackageXmlParser.java
- platform-core/src/main/resources/plugin/plugin-config-v2.xsd
- platform-core/src/test/resources/plugin/sample-plugin-config-v2.xml
- platform-core/src/test/resources/register-for-parser-test.xml
Fixed #1551, allow register,xml to define filter rule
> 1551 support xml define filter rule

- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginPackageDataModelServiceImpl.java
Fixed issue, return entity refByEntites which was slef reference
> 1485 add filter rules

- platform-core/src/main/java/com/webank/wecube/platform/core/support/DomainIdBuilder.java
> #1610 - Fixed #1610, modify generation of resource_item_id

- platform-core/src/main/resources/database/01.wecube.schema.sql
Fixed #1610, modify resource_item_id length from 64 to 255
> #1610 - Fixed #1610, modify resource_item_id length from 64 to 255

- platform-auth-server/src/main/resources/database/02.auth.data.sql
> #1695 - transfer to UTF-8

- platform-core/src/main/resources/database/03.wecube.flow_engine.schema.sql
> #1744 - Fixed #1744, update init sql

- platform-core/src/main/java/com/webank/wecube/platform/core/service/resource/DockerContainerManagementService.java
> 1760 support plugin container auto restart

- platform-core/src/main/java/com/webank/wecube/platform/core/service/SystemVariableService.java
Fixed #1741, set value='' if can not found system variable
> 1741 enhance system variables

- README.md
> #1805 update readme

- platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginRouteItemService.java
get latest version by upload time
> refactor getting all plugin route items for performance

- platform-core/src/main/java/com/webank/wecube/platform/core/dto/MenuItemDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/dto/PluginPackageInfoDto.java
- platform-core/src/main/java/com/webank/wecube/platform/core/lazyDomain/plugin/LazyPluginPackage.java
- platform-core/src/main/java/com/webank/wecube/platform/core/lazyDomain/plugin/LazyPluginPackageMenu.java
- platform-core/src/main/java/com/webank/wecube/platform/core/lazyJpa/LazyPluginPackageMenuRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/lazyJpa/LazyPluginPackageRepository.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/MenuService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/plugin/PluginPackageService.java
- platform-core/src/main/java/com/webank/wecube/platform/core/service/user/RoleMenuServiceImpl.java
- platform-core/src/main/java/com/webank/wecube/platform/core/support/DomainIdBuilder.java
1. myMenus
2. /platform/v1/packages
Create lazy domain and repository classes to improve performance.
> API performance improvement

- Makefile
- build/get_wecube_docs.sh
- build/wecube-portal/Dockerfile
- build/wecube-portal/nginx.tpl
- wecube-portal/src/locale/i18n/en-US.json
- wecube-portal/src/locale/i18n/zh-CN.json
- wecube-portal/src/pages/components/header.vue
> 1889 localdocs

- build/docker-compose.tpl
> #1917 update docker compose file

- wecube-portal/package.json
- wecube-portal/src/locale/i18n/en-US.json
- wecube-portal/src/locale/i18n/zh-CN.json
- wecube-portal/src/pages/components/header.vue
update online doc url(according to locale)
> #1966 update online doc url(according to locale)

- platform-auth-server/pom.xml
- platform-core/pom.xml
- platform-gateway/pom.xml
upgrade spring-security and protobuf-java dependencies
> 20231008 security fix
